/* eslint-disable @typescript-eslint/no-explicit-any */
/*
* Full disclosure:
* Some function names and signatures are from
* https://craftinginterpreters.com/representing-code.html.
* Book copyright by Robert Nystrom. I've included the MIT license that code
* snippets from the book is licensed under down below. See
* https://github.com/munificent/craftinginterpreters/blob/master/LICENSE
*
*
* The changes I've made: I've basically reworked the whole thing:
*     - The book was written in Java. I have written this in TypeScript.
*     - This generates TypeScript code. The book generates Java code.
*     - Added the ability for the generator to format indents properly.
*
* Run this file with `npm run regen`.
*

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to
    deal in the Software without restriction, including without limitation the
    rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
    sell copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
    IN THE SOFTWARE.
**/
import fs from "fs";
import path from "path";

const FILE_NAME: string = path.join(path.resolve(__dirname, "."), "../src/ast-types.ts");

interface FieldOverride {
  fieldType: string;
  constructorType: string;
  transform: string;
}

interface AstWriterConfig {
  additionalImports?: string[];
  typeAliases?: string[];
  fieldOverrides?: Record<string, FieldOverride>;
}

export class AstWriter {
  indentationLevel: number;
  fp?: fs.WriteStream;

  constructor(private config: AstWriterConfig = {}) {
    this.indentationLevel = 0;
  }

  main() {
    this.setup();
    this.defineAst("Expr", [
      "BigIntLiteral -> value: string",
      "Binary    -> left: Expr, operator: Token, right: Expr",
      // Semantically different from Binary - for logical comparisons.
      "Compare   -> left: Expr, operator: Token, right: Expr",
      // For boolean operations
      "BoolOp    -> left: Expr, operator: Token, right: Expr",
      "Grouping  -> expression: Expr",
      "Literal   -> value: true | false | number | string",
      "Unary     -> operator: Token, right: Expr",
      "Ternary   -> predicate: Expr, consequent: Expr, alternative: Expr",
      "Lambda    -> parameters: FunctionParam[], body: Expr",
      "MultiLambda -> parameters: FunctionParam[], body: StmtNS.Stmt[], varDecls: Token[]",
      "Variable  -> name: Token",
      "Call      -> callee: Expr, args: Expr[]",
      "List      -> elements: Expr[]",
      "Subscript -> value: Expr, index: Expr",
      "Starred   -> value: Expr",
      "None      -> ()",
      "Complex   -> value: string",
    ]);
    this.defineAst("Stmt", [
      "Pass       -> ()",
      "Assign     -> target: AssignTarget, value: ExprNS.Expr",
      "AnnAssign  -> target: ExprNS.Variable, value: ExprNS.Expr, ann: ExprNS.Expr",
      "Break      -> ()",
      "Continue   -> ()",
      "Return     -> value: ExprNS.Expr | null",
      "FromImport -> module: Token, names: { name: Token; alias: Token | null }[]",
      "Global     -> name: Token",
      "NonLocal   -> name: Token",
      "Assert     -> value: ExprNS.Expr",
      "If         -> condition: ExprNS.Expr, body: Stmt[], elseBlock: Stmt[] | null",
      "While      -> condition: ExprNS.Expr, body: Stmt[]",
      "For        -> target: Token, iter: ExprNS.Expr, body: Stmt[]",
      "FunctionDef -> name: Token, parameters: FunctionParam[], body: Stmt[], varDecls: Token[]",
      "SimpleExpr  -> expression: ExprNS.Expr",
      // Mainly two types of input - file and interactive (repl)
      "FileInput   -> statements: Stmt[], varDecls: Token[]",
    ]);
    this.tearDown();
  }

  private setup() {
    // Clear the file.
    fs.writeFileSync(FILE_NAME, "");
    this.fp = fs.createWriteStream(FILE_NAME);
    this.writeSingleLine(
      "// This file is autogenerated by generate-ast.ts. DO NOT EDIT THIS FILE DIRECTLY.",
    );
    // Imports
    this.writeSingleLine('import {Token} from "./tokenizer";');
    for (const imp of this.config.additionalImports ?? []) {
      this.writeSingleLine(imp);
    }
    this.writeSingleLine("");
    for (const alias of this.config.typeAliases ?? []) {
      this.writeSingleLine(alias);
    }
  }

  private tearDown() {
    // Check that indentation is correct.
    console.assert(this.indentationLevel == 0, "Indentation level should be 0 at end.");
    this.fp?.close();
  }

  private convertToReadableForm(definitions: string[]) {
    /*
     * Converts to the form:
     * [Name, [[attribute, type], [attribute, type], ...]
     * ...
     * */
    return definitions
      .map(s => s.split("->"))
      .map(pair => [
        pair[0].trim(),
        this.splitFields(pair[1]).map(s => {
          const colonIdx = s.indexOf(":");
          if (colonIdx === -1) return [s.trim()];
          return [s.substring(0, colonIdx).trim(), s.substring(colonIdx + 1).trim()];
        }),
      ]);
  }

  private splitFields(s: string): string[] {
    const fields: string[] = [];
    let depth = 0;
    let current = "";
    for (const c of s) {
      if (c === "{" || c === "(") depth++;
      else if (c === "}" || c === ")") depth--;
      if (c === "," && depth === 0) {
        fields.push(current);
        current = "";
      } else {
        current += c;
      }
    }
    fields.push(current);
    return fields;
  }

  private defineAst(baseClass: string, definitions: any) {
    definitions = this.convertToReadableForm(definitions);
    this.writeSingleLine(`export namespace ${baseClass}NS {`);
    this.defineVisitorInterface(baseClass, definitions);

    // Base class
    this.writeSingleLine(`export abstract class ${baseClass} {`);
    this.writeSingleLine("abstract readonly kind: string;");
    this.writeSingleLine("startToken: Token;");
    this.writeSingleLine("endToken: Token;");
    this.writeSingleLine("protected constructor(startToken: Token, endToken: Token) {");
    this.writeSingleLine("this.startToken = startToken;");
    this.writeSingleLine("this.endToken = endToken;");
    this.writeSingleLine("}");
    this.writeSingleLine("abstract accept(visitor: Visitor<any>): any;");
    this.writeSingleLine("}");

    // Classes
    for (const classDefinition of definitions) {
      const [className, attributes] = classDefinition;
      const isEmpty = attributes[0][0] === "()";
      this.classDef(baseClass, className, attributes, isEmpty);
    }
    this.writeSingleLine("");
    this.writeSingleLine("");
    this.writeSingleLine("}");
  }

  private classDef(baseClass: string, name: string, attributes: string[], isEmpty: boolean) {
    this.writeSingleLine(`export class ${name} extends ${baseClass} {`);
    this.writeSingleLine(`readonly kind = "${name}";`);
    if (!isEmpty) {
      for (const [fieldName, fieldType] of attributes) {
        const override = this.config.fieldOverrides?.[name + "." + fieldName];
        this.writeSingleLine(`${fieldName}: ${override ? override.fieldType : fieldType};`);
      }
    }
    let parameters = !isEmpty
      ? ", " +
        attributes
          .map(attribute => {
            const override = this.config.fieldOverrides?.[name + "." + attribute[0]];
            return `${attribute[0]}: ${override ? override.constructorType : attribute[1]}`;
          })
          .join(", ")
      : "";
    parameters = "startToken: Token, endToken: Token" + parameters;
    this.writeSingleLine(`constructor(${parameters}){`);
    this.writeSingleLine("super(startToken, endToken)");
    if (!isEmpty) {
      for (const attribute of attributes) {
        const fieldName = attribute[0];
        const override = this.config.fieldOverrides?.[name + "." + fieldName];
        if (override) {
          this.writeSingleLine(`this.${fieldName} = ${override.transform};`);
        } else {
          this.writeSingleLine(`this.${fieldName} = ${fieldName};`);
        }
      }
    }
    this.writeSingleLine("}");
    // Visitor pattern
    this.writeSingleLine("override accept(visitor: Visitor<any>): any {");
    this.writeSingleLine(`return visitor.visit${name}${baseClass}(this)`);
    this.writeSingleLine("}");
    this.writeSingleLine("}");
  }

  private defineVisitorInterface(baseClass: string, definitions: any) {
    this.writeSingleLine(`export interface Visitor<T> {`);
    for (const classDefinition of definitions) {
      const className = classDefinition[0];
      this.writeSingleLine(
        `visit${className}${baseClass}(${baseClass.toLowerCase()}: ${className}): T`,
      );
    }
    this.writeSingleLine("}");
  }

  private indent() {
    this.indentationLevel += 4;
  }

  private dedent() {
    this.indentationLevel -= 4;
  }

  private writeSingleLine(chunk: string) {
    if (this.fp === undefined) {
      throw new Error("File not initialised");
    }
    const dedentFirst = chunk.startsWith("}") || chunk.startsWith(")") ? 1 : 0;
    if (dedentFirst) {
      this.dedent();
    }
    this.fp.write("".padEnd(this.indentationLevel, " "));
    this.fp.write(chunk);
    this.fp.write("\n");
    for (let i = dedentFirst; i < chunk.length; ++i) {
      const c = chunk[i];
      switch (c) {
        case "{":
        case "(":
          this.indent();
          continue;
        case "}":
        case ")":
          this.dedent();
      }
    }
  }

  writeRaw(chunk: string) {
    if (this.fp === undefined) {
      throw new Error("File not initialised");
    }
    this.fp.write(chunk);
  }
}
