# Credits to https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# for the code.

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run format:ci
      - run: yarn run lint
      - run: yarn run test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
